### ISSUE TITLE
Parcel não está dando watch na pasta data

### ISSUE THREAD

**Issue by MatheusMoura17** [Eletrodos/full-command#10]
A pasta data contém os arquivos json com a descrição e nome dos comandos, porém a mesma é copiada e colada para dentro da pasta dist.
O parcel não está assistindo as alterações dos arquivos desta pasta.

**Comment by RodrigoBastos** [comment]
Essa ação é necessária? 

Vi aqui que o arquivo json está como assets da aplicação.

**Comment by MatheusMoura17** [comment]
Tem razão, esses arquivos são estáticos.
